'use strict';

/**
 * lib/report-archive.js — storing and serving published board reports.
 *
 * Structured like lib/report-pptx-route.js, and for the same reason: the
 * handlers take their dependencies as arguments so a test can mount them over
 * real HTTP without a database or a filesystem of real decks.
 *
 * ── WHAT A PUBLISH IS ─────────────────────────────────────────────────────
 *
 * Staff assemble a deck in the browser, review it, and publish. The bytes we
 * store are built from the SAME assembled sections the preview used — publish
 * never re-fetches, because a report that quietly differs from the one someone
 * approved is worse than no archive at all.
 *
 * ── WHERE THE BYTES LIVE ──────────────────────────────────────────────────
 *
 * Filesystem, with the row as the index. See db/migrate-report-archive.sql for
 * why not bytea and why not object storage. The path is always generated here
 * and is still re-validated by resolveArchivePath() before every open, because
 * "we generated it" is an assumption and a traversal check is a fact.
 */

const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

const pptxRoute = require('./report-pptx-route');
const { buildPptx } = require('./report-pptx');

/**
 * Where archived decks live.
 *
 * MUST NOT be under public/. express.static is mounted before the session
 * middleware, so anything below public/ is served to anonymous callers — an
 * archive there would publish every client's board report to the internet.
 */
const ARCHIVE_DIR = process.env.REPORT_ARCHIVE_DIR ||
  path.join(__dirname, '..', 'data', 'reports');

/** Superseded and withdrawn files are unlinked after this. Rows are kept. */
const KEEP_DAYS = parseInt(process.env.REPORT_ARCHIVE_KEEP_DAYS, 10) || 730;

/** deck_html above this is dropped; the pptx is still archived. */
const MAX_HTML_BYTES = 4 * 1024 * 1024;

/* ── Paths ────────────────────────────────────────────────────────────────── */

/**
 * Resolve a stored relative path to an absolute one, refusing anything that
 * escapes the archive root.
 *
 * The stored value is generated by this module and never comes from a client,
 * so in principle traversal is impossible. This exists because that reasoning
 * depends on every future caller also being careful, and a path check does not.
 */
function resolveArchivePath(relative) {
  if (!relative || typeof relative !== 'string') return null;
  const root = path.resolve(ARCHIVE_DIR);
  const abs = path.resolve(root, relative);
  if (abs !== root && !abs.startsWith(root + path.sep)) return null;
  return abs;
}

/** A download filename: the tenant's, the period's, and the version's. */
function archiveFilename(row) {
  const base = pptxRoute.pptxFilename({
    clientName: row.client_name,
    period: row.period,
    periodLabel: row.period_label,
  }).replace(/\.pptx$/i, '');
  return base + '-v' + (row.version || 1) + '.pptx';
}

/* ── Publishing ───────────────────────────────────────────────────────────── */

function sha256(buffer) {
  return crypto.createHash('sha256').update(buffer).digest('hex');
}

/**
 * createPublishHandler — POST /api/reports/publish
 *
 * @param {Object} deps
 *   pool           pg pool
 *   resolveTenant  (req) => { tenantId, error }
 *   logoDataUri    passed through to buildPptx
 *   onError        (res, err) => void
 */
function createPublishHandler(deps) {
  const { pool, resolveTenant, logoDataUri, onError } = deps;

  return async function publishReport(req, res) {
    let writtenPath = null;
    try {
      const { tenantId, error: tenantErr } = resolveTenant(req);
      if (tenantErr) return res.status(tenantErr.status).json({ error: tenantErr.message });

      // Reuse the pptx route's clamping verbatim rather than writing a second
      // validator that can drift from it.
      const clean = pptxRoute.sanitiseRequest(req.body);
      if (clean.error) return res.status(clean.status || 400).json({ error: clean.error });

      const period = String((req.body && req.body.period) || clean.ctx.period || '').slice(0, 7);
      if (!/^\d{4}-\d{2}$/.test(period)) {
        return res.status(400).json({ error: 'A period of the form YYYY-MM is required.' });
      }

      // The logo rides on ctx, exactly as createPptxHandler does it — calling
      // buildPptx a second way would give the archived deck different branding
      // from the one staff previewed.
      const buildCtx = Object.assign({}, clean.ctx,
        { logoDataUri: typeof logoDataUri === 'function' ? logoDataUri() : logoDataUri });
      const built = await buildPptx(buildCtx, clean.sections);
      const buffer = built && built.buffer;
      if (!Buffer.isBuffer(buffer)) {
        return res.status(500).json({ error: 'Report build produced no file.' });
      }

      // Write to a temp name and rename: a reader can never observe a partial
      // file, because rename within a filesystem is atomic.
      const dir = path.join(path.resolve(ARCHIVE_DIR), String(tenantId));
      fs.mkdirSync(dir, { recursive: true });
      const stem = period + '-' + crypto.randomUUID() + '.pptx';
      const tmp = path.join(dir, stem + '.tmp');
      const abs = path.join(dir, stem);
      fs.writeFileSync(tmp, buffer);
      fs.renameSync(tmp, abs);
      writtenPath = abs;
      const rel = path.relative(path.resolve(ARCHIVE_DIR), abs);

      let html = typeof (req.body && req.body.deckHtml) === 'string' ? req.body.deckHtml : null;
      let htmlBytes = html ? Buffer.byteLength(html, 'utf8') : null;
      if (htmlBytes && htmlBytes > MAX_HTML_BYTES) {
        // The pptx is still archived; the portal offers download-only.
        html = null;
        htmlBytes = null;
      }

      const title = String((req.body && req.body.title) || '').slice(0, 300);
      const note  = String((req.body && req.body.coverNote) || '').slice(0, 4000);

      // version comes from a scalar subquery in the same statement, so two
      // concurrent publishes collide on the unique index instead of silently
      // sharing a version number.
      const insert = () => pool.query(
        `INSERT INTO report_publications
           (tenant_id, period, version, title, client_name, period_label, author,
            cover_note, published_by, pptx_path, pptx_bytes, pptx_sha256,
            slide_count, deck_html, html_bytes, sections, ctx)
         VALUES ($1, $2,
                 (SELECT COALESCE(MAX(version), 0) + 1 FROM report_publications
                   WHERE tenant_id = $1 AND period = $2),
                 $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16)
         RETURNING id, period, version, title, published_at, pptx_bytes, slide_count`,
        [tenantId, period, title, clean.ctx.clientName, clean.ctx.periodLabel,
         clean.ctx.author, note, (req.session && req.session.userId) || null,
         rel, buffer.length, sha256(buffer),
         (built && built.stats && built.stats.slides) || null,
         html, htmlBytes,
         JSON.stringify(clean.sections), JSON.stringify(clean.ctx)]
      );

      let result;
      try {
        result = await insert();
      } catch (err) {
        if (err.code !== '23505') throw err;   // unique_violation — lost the race
        result = await insert();
      }

      writtenPath = null;   // committed; no longer ours to clean up
      return res.status(201).json({ publication: result.rows[0] });
    } catch (err) {
      // The row never landed, so the file is an orphan. Best-effort removal;
      // sweepOrphanReportFiles() is the backstop for the crash case.
      if (writtenPath) { try { fs.unlinkSync(writtenPath); } catch (_) { /* swept later */ } }
      if (onError) return onError(res, err);
      return res.status(500).json({ error: err.message });
    }
  };
}

/* ── Reading ──────────────────────────────────────────────────────────────── */

/** Columns safe to list. Deliberately excludes deck_html and sections: both are
 *  large, and a listing that ships megabytes per row is a listing nobody uses. */
const LIST_COLUMNS = `id, period, version, title, client_name, period_label,
  cover_note, status, published_at, pptx_bytes, slide_count, purged_at,
  (deck_html IS NOT NULL) AS has_html,
  download_count, last_downloaded_at`;

/**
 * listPublications — the archive for one tenant.
 *
 * `publishedOnly` is what the portal passes: a withdrawn report disappears for
 * the client but stays visible to staff with its reason.
 */
async function listPublications(pool, opts) {
  const o = opts || {};
  const params = [o.tenantId];
  let where = 'tenant_id = $1';

  if (o.publishedOnly) where += " AND status = 'published'";
  if (o.period) { params.push(o.period); where += ' AND period = $' + params.length; }

  const r = await pool.query(
    `SELECT ${LIST_COLUMNS} FROM report_publications
      WHERE ${where}
      ORDER BY period DESC, version DESC`,
    params
  );

  // "Latest" is per period, so an older period's newest version is not marked
  // superseded just because a newer period exists.
  const seen = new Set();
  return r.rows.map((row) => {
    const isLatest = !seen.has(row.period);
    seen.add(row.period);
    return Object.assign({}, row, { isLatest });
  });
}

/**
 * Fetch one publication with the ownership check IN THE QUERY.
 *
 * Not a post-fetch `if (row.tenant_id !== tenantId)`: with the check in the
 * WHERE clause, another tenant's id and a nonexistent id are indistinguishable,
 * both returning null and therefore both 404.
 */
async function getPublication(pool, id, tenantId, opts) {
  const o = opts || {};
  const cols = o.withHtml ? LIST_COLUMNS + ', deck_html, pptx_path' : LIST_COLUMNS + ', pptx_path';
  const params = [id, tenantId];
  let where = 'id = $1 AND tenant_id = $2';
  if (o.publishedOnly) where += " AND status = 'published'";

  const r = await pool.query(
    `SELECT ${cols} FROM report_publications WHERE ${where}`, params);
  return r.rows[0] || null;
}

/** Stream the archived .pptx. Shared by the staff and portal routes. */
function sendPublicationPptx(res, row) {
  const abs = resolveArchivePath(row.pptx_path);
  if (!abs) return res.status(410).json({ error: 'Archived file is no longer available.' });

  let size = row.pptx_bytes;
  try {
    // Prefer the on-disk size. A disagreement means the file was truncated or
    // replaced, and a wrong Content-Length would hang or corrupt the download.
    const stat = fs.statSync(abs);
    if (stat.size !== row.pptx_bytes) {
      console.warn('[report-archive] size mismatch for publication', row.id,
        'row=' + row.pptx_bytes, 'disk=' + stat.size);
    }
    size = stat.size;
  } catch (_) {
    return res.status(410).json({ error: 'Archived file is no longer available.' });
  }

  const name = archiveFilename(row);
  res.setHeader('Content-Type', pptxRoute.PPTX_MIME);
  res.setHeader('Content-Disposition',
    'attachment; filename="' + name + '"; filename*=UTF-8\'\'' + encodeURIComponent(name));
  res.setHeader('Content-Length', size);
  res.setHeader('X-Content-Type-Options', 'nosniff');
  res.setHeader('Cache-Control', 'private, no-store');

  const stream = fs.createReadStream(abs);
  stream.on('error', () => {
    if (!res.headersSent) res.status(410).json({ error: 'Archived file is no longer available.' });
    else res.destroy();
  });
  return stream.pipe(res);
}

/**
 * Serve the archived HTML.
 *
 * The document carries report-deck.js's inline pagination script. Served
 * same-origin that script would sit inside the portal's cookie scope, so the
 * CSP `sandbox` directive forces an opaque origin: the script still runs and
 * window.print() still works, but it can read no cookies and make no
 * same-origin request.
 */
const ARCHIVE_HTML_CSP = [
  "sandbox allow-scripts allow-popups allow-modals allow-downloads",
  "default-src 'none'",
  "style-src 'unsafe-inline'",
  "img-src data:",
  "font-src data:",
  "script-src 'unsafe-inline'",
].join('; ');

function sendPublicationHtml(res, row) {
  if (!row.deck_html) {
    return res.status(404).json({ error: 'No viewable version was archived for this report.' });
  }
  res.setHeader('Content-Type', 'text/html; charset=utf-8');
  res.setHeader('Content-Security-Policy', ARCHIVE_HTML_CSP);
  res.setHeader('X-Content-Type-Options', 'nosniff');
  res.setHeader('Cache-Control', 'private, no-store');
  res.setHeader('Content-Disposition',
    'inline; filename="' + archiveFilename(row).replace(/\.pptx$/, '.html') + '"');
  return res.end(row.deck_html);
}

/** Count a delivery. Fire-and-forget, and only AFTER the stream finished. */
function noteDownload(pool, id) {
  pool.query(
    `UPDATE report_publications
        SET download_count = download_count + 1, last_downloaded_at = NOW()
      WHERE id = $1`, [id]
  ).catch(() => { /* a missed counter must never fail a download */ });
}

/* ── Retention ────────────────────────────────────────────────────────────── */

/**
 * Unlink files for superseded and withdrawn versions past the retention window.
 * The ROW SURVIVES: the record of what was sent to whom outlives the bytes.
 * The newest version of every period is kept indefinitely.
 */
async function pruneReportArchive(pool) {
  let removed = 0;
  try {
    const r = await pool.query(
      `SELECT id, pptx_path FROM report_publications p
        WHERE pptx_path IS NOT NULL
          AND published_at < NOW() - ($1 || ' days')::interval
          AND (status = 'withdrawn'
               OR version < (SELECT MAX(version) FROM report_publications q
                              WHERE q.tenant_id = p.tenant_id AND q.period = p.period))`,
      [String(KEEP_DAYS)]
    );

    for (const row of r.rows) {
      const abs = resolveArchivePath(row.pptx_path);
      if (abs) { try { fs.unlinkSync(abs); } catch (_) { /* already gone */ } }
      await pool.query(
        `UPDATE report_publications SET pptx_path = NULL, purged_at = NOW() WHERE id = $1`,
        [row.id]);
      removed++;
    }
  } catch (err) {
    if (err.code !== '42P01') throw err;   // archive not migrated yet
  }
  return removed;
}

/**
 * Remove archive files with no owning row — the remnant of a publish that
 * crashed between writing the file and committing the row.
 */
async function sweepOrphanReportFiles(pool) {
  const root = path.resolve(ARCHIVE_DIR);
  if (!fs.existsSync(root)) return 0;

  let known;
  try {
    const r = await pool.query('SELECT pptx_path FROM report_publications WHERE pptx_path IS NOT NULL');
    known = new Set(r.rows.map(x => path.resolve(root, x.pptx_path)));
  } catch (err) {
    // Without the table we cannot tell an orphan from a live file, and
    // deleting on a guess is the one outcome worth avoiding.
    if (err.code === '42P01') return 0;
    throw err;
  }

  let removed = 0;
  for (const tenantDir of fs.readdirSync(root, { withFileTypes: true })) {
    if (!tenantDir.isDirectory()) continue;
    const dir = path.join(root, tenantDir.name);
    for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
      if (!entry.isFile()) continue;
      const abs = path.join(dir, entry.name);
      // .tmp files are always remnants: the real name is only ever reached by
      // rename, so a surviving .tmp means the publish did not finish.
      if (!known.has(abs) || abs.endsWith('.tmp')) {
        try { fs.unlinkSync(abs); removed++; } catch (_) { /* leave it */ }
      }
    }
  }
  return removed;
}

module.exports = {
  ARCHIVE_DIR,
  KEEP_DAYS,
  MAX_HTML_BYTES,
  ARCHIVE_HTML_CSP,
  LIST_COLUMNS,
  resolveArchivePath,
  archiveFilename,
  createPublishHandler,
  listPublications,
  getPublication,
  sendPublicationPptx,
  sendPublicationHtml,
  noteDownload,
  pruneReportArchive,
  sweepOrphanReportFiles,
};
