-- GRC Realignment Migration: replace 36-question bank with a 55-question bank
-- aligned 1:1 to IT_Risk_Register_Full_View.xlsx (ITR-001..ITR-055), grouped into
-- 22 spreadsheet domains. DESTRUCTIVE to existing GRC assessment data.
-- Run once: psql -d secops -f migrate-grc-realign.sql

-- 1. Schema additions ───────────────────────────────────────────────────────
ALTER TABLE grc_questions
  ADD COLUMN IF NOT EXISTS external_risk_id   VARCHAR(20),
  ADD COLUMN IF NOT EXISTS risk_title          VARCHAR(200),
  ADD COLUMN IF NOT EXISTS default_category    VARCHAR(50),
  ADD COLUMN IF NOT EXISTS default_likelihood  SMALLINT,
  ADD COLUMN IF NOT EXISTS default_impact      SMALLINT,
  ADD COLUMN IF NOT EXISTS default_owner       VARCHAR(200),
  ADD COLUMN IF NOT EXISTS default_mitigation  TEXT;

DO $$ BEGIN
  ALTER TABLE grc_questions ADD CONSTRAINT chk_default_category
    CHECK (default_category IS NULL OR default_category IN
      ('operational','financial','compliance','technical','reputational'));
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE grc_questions ADD CONSTRAINT chk_default_likelihood
    CHECK (default_likelihood IS NULL OR default_likelihood BETWEEN 1 AND 5);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE grc_questions ADD CONSTRAINT chk_default_impact
    CHECK (default_impact IS NULL OR default_impact BETWEEN 1 AND 5);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

ALTER TABLE risks ADD COLUMN IF NOT EXISTS grc_question_id INT
  REFERENCES grc_questions(id) ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS idx_risks_grc_question ON risks(tenant_id, grc_question_id);

-- 2. Clear existing GRC data (destructive, explicit) ────────────────────────
-- grc_assessments has no FK to grc_questions, so it will not cascade -- must
-- clear explicitly since its grc_score is meaningless against the new bank.
-- Deleting grc_assessments cascades to grc_answers (FK assessment_id).
DELETE FROM grc_assessments;
-- Deleting grc_questions cascades to any remaining grc_answers (belt & suspenders).
DELETE FROM grc_questions;

CREATE UNIQUE INDEX IF NOT EXISTS idx_grc_questions_external_risk_id
  ON grc_questions(external_risk_id) WHERE external_risk_id IS NOT NULL;

-- 3. New 55-question seed data, 1:1 with IT_Risk_Register_Full_View.xlsx ────
INSERT INTO grc_questions
  (section, order_num, text, weight, help_text, itoo_ref, nist_ref,
   external_risk_id, risk_title, default_category, default_likelihood,
   default_impact, default_owner, default_mitigation)
VALUES
  ('Governance & Strategy', 1, 'Is there an approved, documented IT/security strategy in place?', 'medium', 'IT projects are executed without a clear roadmap or security priorities. Root causes: No approved IT strategy; weak executive sponsorship; limited budget planning.', 'IT Governance', 'NIST CSF GV; ISO 27001 Clause 5/6', 'ITR-001', 'Lack of approved IT/security strategy', 'compliance', 3, 4, 'CIO / IT Manager', 'Define an IT/security roadmap, assign owners, and review quarterly.'),
  ('Governance & Strategy', 2, 'Are IT policies current, approved, and reviewed on a regular cycle?', 'medium', 'Users and administrators operate without current acceptable use, access, and security policies. Root causes: Policies not reviewed; unclear ownership; no document control.', 'Policy Management', 'NIST CSF GV.PO; ISO 27001 A.5', 'ITR-002', 'Outdated or missing IT policies', 'compliance', 3, 3, 'IT Governance / Compliance', 'Create policy register and review schedule with version control.'),
  ('Governance & Strategy', 3, 'Is there a formal, tracked IT risk register with ownership and review cadence?', 'high', 'Risks are known informally but not documented, rated, owned, or tracked to closure. Root causes: No risk methodology; no ownership; no review cadence.', 'Risk Management', 'NIST CSF GV.RM; ISO 27001 Clause 6', 'ITR-003', 'No formal IT risk register', 'compliance', 4, 4, 'Risk Owner / IT Manager', 'Implement a risk register with monthly review and escalation.'),
  ('Identity & Access', 1, 'Is a strong password policy enforced across all accounts?', 'high', 'Users can set weak passwords or reuse compromised passwords. Root causes: Legacy password policy; no password protection; no user education.', 'Identity & Access Management', 'NIST CSF PR.AA; ISO 27001 A.5/A.8', 'ITR-004', 'Weak password controls', 'technical', 4, 4, 'IT Security Manager', 'Enforce strong authentication and monitor risky sign-ins.'),
  ('Identity & Access', 2, 'Is multi-factor authentication (MFA) enforced for all users?', 'critical', 'Remote access or cloud apps allow single-factor authentication. Root causes: MFA rollout incomplete; exceptions not reviewed; poor change management.', 'Identity & Access Management', 'NIST CSF PR.AA; ISO 27001 A.5/A.8', 'ITR-005', 'MFA not enforced for all users', 'technical', 4, 5, 'IT Security Manager', 'Enforce MFA for all users, especially admins and remote access.'),
  ('Identity & Access', 3, 'Are user accounts promptly disabled/removed when no longer needed (no orphaned accounts)?', 'critical', 'Leavers retain active accounts after termination. Root causes: Manual offboarding; HR/IT integration gaps; no periodic access reviews.', 'Identity Lifecycle', 'NIST CSF PR.AA; ISO 27001 A.5.18', 'ITR-006', 'Orphaned user accounts', 'technical', 4, 5, 'IT Operations / HR', 'Implement formal offboarding SLA and monthly dormant-account review.'),
  ('Identity & Access', 4, 'Is user access reviewed regularly to prevent excessive permissions?', 'high', 'Users have access beyond their job role or business need. Root causes: No role-based access model; ad hoc approvals; no reviews.', 'Access Management', 'NIST CSF PR.AA; ISO 27001 A.5.15/A.5.18', 'ITR-007', 'Excessive user permissions', 'technical', 4, 4, 'System Owners', 'Perform role-based access review for critical systems.'),
  ('Privileged Access', 1, 'Are administrator accounts individually assigned rather than shared?', 'high', 'Multiple administrators use one shared privileged account. Root causes: Legacy admin practices; no PAM tooling; no accountability.', 'Privileged Access Management', 'NIST CSF PR.AA; ISO 27001 A.8', 'ITR-008', 'Shared administrator accounts', 'technical', 3, 5, 'IT Security Manager', 'Remove shared admin accounts and enforce named privileged identities.'),
  ('Privileged Access', 2, 'Is standing/persistent global admin access avoided (just-in-time elevation used instead)?', 'high', 'Administrators permanently hold high-level privileges. Root causes: No JIT/JEA model; operational convenience; weak change control.', 'Privileged Access Management', 'NIST CSF PR.AA; ISO 27001 A.8', 'ITR-009', 'Standing global admin privileges', 'technical', 3, 5, 'IT Security Manager', 'Apply JIT access and review all privileged roles monthly.'),
  ('Endpoint & Server', 1, 'Are endpoints patched in line with policy SLAs?', 'critical', 'Laptops and desktops are missing critical OS or application patches. Root causes: Patch process gaps; unmanaged devices; user deferrals.', 'Endpoint Security', 'NIST CSF PR.PS; ISO 27001 A.8.8', 'ITR-010', 'Unpatched endpoints', 'technical', 4, 5, 'Endpoint Manager', 'Define patch SLAs and monitor patch compliance weekly.'),
  ('Endpoint & Server', 2, 'Are all operating systems in use currently supported/vendor-patched?', 'high', 'Legacy systems remain in production after vendor support ends. Root causes: Application dependency; budget constraints; no lifecycle planning.', 'Endpoint Security', 'NIST CSF ID.AM/PR.PS; ISO 27001 A.8.8', 'ITR-011', 'Unsupported operating systems', 'technical', 3, 5, 'Infrastructure Manager', 'Create an exception register and modernization plan for legacy systems.'),
  ('Endpoint & Server', 3, 'Is endpoint protection enabled and correctly configured on all endpoints?', 'high', 'Security agents are inactive, outdated, or not deployed to all endpoints. Root causes: Agent deployment failures; tamper protection disabled; no monitoring.', 'Malware Protection', 'NIST CSF PR.PS/DE.CM; ISO 27001 A.8', 'ITR-012', 'Endpoint protection disabled or misconfigured', 'technical', 3, 5, 'SecOps / Endpoint Manager', 'Track endpoint protection health and remediate non-compliant devices.'),
  ('Email & Collaboration', 1, 'Are controls in place to prevent Business Email Compromise?', 'critical', 'Attacker compromises mailbox or spoofs supplier to redirect payments. Root causes: Weak MFA; poor email authentication; user susceptibility.', 'Email Security', 'NIST CSF PR.DS/DE.CM; ISO 27001 A.5/A.8', 'ITR-013', 'Business Email Compromise', 'technical', 4, 5, 'IT Security / Finance', 'Strengthen email authentication and finance call-back controls.'),
  ('Email & Collaboration', 2, 'Do email security controls reliably catch phishing before it reaches users?', 'high', 'Malicious emails reach users and lead to credential capture or malware. Root causes: Email filtering gaps; new phishing campaigns; limited awareness.', 'Email Security', 'NIST CSF PR.AT/DE.CM; ISO 27001 A.6/A.8', 'ITR-014', 'Phishing emails bypass controls', 'technical', 4, 4, 'SecOps', 'Run phishing simulations and tune email protection controls.'),
  ('Email & Collaboration', 3, 'Is external file/data sharing in collaboration tools properly configured and controlled?', 'medium', 'Sensitive files are shared externally without approval or expiry. Root causes: Default open sharing; no data classification; weak DLP.', 'Collaboration Security', 'NIST CSF PR.DS; ISO 27001 A.5/A.8', 'ITR-015', 'External sharing misconfigured', 'technical', 3, 4, 'M365 / Collaboration Owner', 'Review external sharing settings and apply sensitivity labels.'),
  ('People & Awareness', 1, 'Do employees demonstrate strong security awareness (e.g. via training/phishing test results)?', 'medium', 'Users click phishing links or mishandle sensitive data. Root causes: No awareness programme; limited role-based training.', 'Security Awareness', 'NIST CSF PR.AT; ISO 27001 A.6', 'ITR-016', 'Low security awareness', 'operational', 4, 3, 'Security Awareness Lead', 'Run ongoing awareness with metrics and executive reporting.'),
  ('People & Awareness', 2, 'Are controls in place to detect and prevent insider (malicious or negligent) activity?', 'medium', 'Employee intentionally or accidentally exposes sensitive information. Root causes: Excessive access, disgruntlement, poor monitoring.', 'Insider Risk', 'NIST CSF PR.AA/DE.CM; ISO 27001 A.5/A.6', 'ITR-017', 'Malicious or negligent insider activity', 'operational', 2, 5, 'HR / IT Security', 'Implement insider-risk monitoring aligned to privacy and HR processes.'),
  ('Network & Infrastructure', 1, 'Is the internal network segmented (not flat)?', 'high', 'Critical systems and user devices are on the same network segment. Root causes: Legacy design; limited segmentation; firewall rule sprawl.', 'Network Security', 'NIST CSF PR.IR/PR.PS; ISO 27001 A.8', 'ITR-018', 'Flat internal network', 'technical', 3, 5, 'Network Manager', 'Segment critical systems and enforce restricted traffic flows.'),
  ('Network & Infrastructure', 2, 'Are firewall rules reviewed and correctly configured?', 'high', 'Overly permissive firewall rules expose services unnecessarily. Root causes: Poor rule review; emergency changes; no recertification.', 'Firewall Management', 'NIST CSF PR.PS; ISO 27001 A.8', 'ITR-019', 'Firewall misconfiguration', 'technical', 3, 5, 'Network Manager', 'Perform quarterly firewall rule recertification.'),
  ('Network & Infrastructure', 3, 'Is remote access (VPN/RDP) secured (e.g. MFA, restricted, monitored)?', 'high', 'Remote access lacks MFA, device compliance, or logging. Root causes: Legacy VPN; weak access controls; unmanaged endpoints.', 'Remote Access', 'NIST CSF PR.AA; ISO 27001 A.8', 'ITR-020', 'Insecure VPN or remote access', 'technical', 3, 5, 'Network / Security Manager', 'Require MFA and compliant device checks for remote access.'),
  ('Network & Infrastructure', 4, 'Is internet connectivity resilient against outage (e.g. redundant links)?', 'medium', 'Primary ISP outage disrupts cloud and business services. Root causes: Single ISP; no failover; weak monitoring.', 'Availability', 'NIST CSF PR.IR/RC.RP; ISO 27001 A.5', 'ITR-021', 'Internet connectivity failure', 'technical', 3, 4, 'Infrastructure Manager', 'Implement resilient connectivity and test failover.'),
  ('Network & Infrastructure', 5, 'Are DDoS protections in place for internet-facing services?', 'medium', 'Public-facing services become unavailable due to volumetric traffic. Root causes: No DDoS protection; insufficient capacity; exposed services.', 'DDoS / Availability', 'NIST CSF PR.IR/DE.CM; ISO 27001 A.8', 'ITR-022', 'Denial-of-service attack', 'technical', 2, 5, 'Infrastructure / Security', 'Assess DDoS exposure for critical internet-facing services.'),
  ('Cloud & SaaS', 1, 'Is the cloud tenant configuration regularly reviewed to prevent misconfiguration?', 'critical', 'Cloud services allow risky access, weak admin controls, or exposed data. Root causes: Default settings; limited cloud governance; no baseline standard.', 'Cloud Security', 'NIST CSF PR.PS/DE.CM; ISO 27001 A.8', 'ITR-023', 'Cloud tenant misconfiguration', 'technical', 4, 5, 'Cloud Platform Owner', 'Implement a cloud security baseline and monitor posture monthly.'),
  ('Cloud & SaaS', 2, 'Is SaaS usage governed to prevent shadow IT?', 'high', 'Departments use unapproved SaaS apps to process business data. Root causes: Fast procurement; no SaaS review; weak visibility.', 'SaaS Governance', 'NIST CSF GV.SC/ID.AM; ISO 27001 A.5', 'ITR-024', 'Shadow IT / unmanaged SaaS usage', 'technical', 4, 4, 'IT Governance / Procurement', 'Create SaaS register and require security review before adoption.'),
  ('Cloud & SaaS', 3, 'Is cloud service resilience/failover adequately planned for?', 'medium', 'A major cloud or SaaS provider outage affects critical business processes. Root causes: High cloud dependency; no contingency plan.', 'Cloud Resilience', 'NIST CSF RC.RP; ISO 27001 A.5/A.8', 'ITR-025', 'Cloud service outage', 'technical', 3, 4, 'Business Owner / IT', 'Document contingency processes for critical SaaS platforms.'),
  ('Applications', 1, 'Are web applications tested and secured against common vulnerabilities?', 'high', 'Application has exploitable flaws such as injection, broken auth, or exposed APIs. Root causes: No secure SDLC; insufficient testing; legacy code.', 'Application Security', 'NIST CSF PR.PS/DE.CM; ISO 27001 A.8.25/A.8.28', 'ITR-026', 'Vulnerable web application', 'technical', 3, 5, 'Application Owner', 'Introduce security testing into the SDLC and release gates.'),
  ('Applications', 2, 'Is production change managed through a controlled change process?', 'medium', 'Changes are made without review, testing, or rollback plans. Root causes: Weak CAB process; emergency changes; poor segregation.', 'Change Management', 'NIST CSF PR.PS; ISO 27001 A.8.32', 'ITR-027', 'Uncontrolled production changes', 'technical', 3, 4, 'Change Manager', 'Enforce change approval and emergency-change review.'),
  ('Applications', 3, 'Are APIs properly authenticated, authorized, and protected?', 'high', 'APIs expose sensitive data or allow unauthorized access. Root causes: Poor authentication; no inventory; no rate limiting.', 'API Security', 'NIST CSF PR.AA/PR.PS; ISO 27001 A.8', 'ITR-028', 'Exposed or weakly protected APIs', 'technical', 3, 5, 'Application / Integration Owner', 'Inventory APIs and apply authentication, authorization, and logging.'),
  ('Vulnerability Management', 1, 'Is regular vulnerability scanning performed across the environment?', 'critical', 'The environment is not scanned for known vulnerabilities. Root causes: No scanning tool; unclear scope; no process.', 'Vulnerability Management', 'NIST CSF ID.RA/PR.PS; ISO 27001 A.8.8', 'ITR-029', 'No regular vulnerability scanning', 'technical', 4, 5, 'Vulnerability Manager', 'Implement recurring scans and remediation SLAs.'),
  ('Vulnerability Management', 2, 'Are critical vulnerabilities remediated within policy SLAs (no backlog)?', 'critical', 'Critical vulnerabilities remain open beyond agreed timelines. Root causes: Resource constraints; poor ownership; change windows unavailable.', 'Patch & Remediation', 'NIST CSF PR.PS; ISO 27001 A.8.8', 'ITR-030', 'Critical vulnerability backlog', 'technical', 4, 5, 'Vulnerability Manager / System Owners', 'Prioritize internet-facing and critical-system vulnerabilities.'),
  ('Monitoring & Detection', 1, 'Is security logging sufficient across critical systems?', 'high', 'Critical systems do not produce or retain security logs. Root causes: Misconfigured logging; storage limits; no logging standard.', 'Logging', 'NIST CSF DE.CM; ISO 27001 A.8.15/A.8.16', 'ITR-031', 'Insufficient security logging', 'technical', 3, 5, 'SecOps / Platform Owners', 'Define mandatory log sources and retention by system criticality.'),
  ('Monitoring & Detection', 2, 'Is there 24/7 monitoring (SOC/MDR) for critical security alerts?', 'high', 'High-severity alerts are not monitored outside business hours. Root causes: Limited staffing; no MDR/SOC arrangement; no escalation path.', 'SIEM / SOC', 'NIST CSF DE.CM/RS.MA; ISO 27001 A.8.16', 'ITR-032', 'No 24/7 monitoring for critical alerts', 'technical', 3, 5, 'SecOps Manager', 'Establish monitoring coverage and response SLAs for critical alerts.'),
  ('Monitoring & Detection', 3, 'Are security alerts effectively tuned to avoid alert fatigue?', 'medium', 'Too many low-value alerts cause analysts to miss true positives. Root causes: Poor tuning; duplicate telemetry; no use-case review.', 'Alert Management', 'NIST CSF DE.CM; ISO 27001 A.8.16', 'ITR-033', 'Alert fatigue and poor tuning', 'technical', 3, 4, 'SecOps Manager', 'Review high-volume alerts monthly and tune detections.'),
  ('Incident Response', 1, 'Has the incident response plan been tested/exercised?', 'high', 'Teams are unsure how to respond during a cyber incident. Root causes: Plan not documented; no tabletop exercises; unclear roles.', 'Incident Response', 'NIST CSF RS/RC; ISO 27001 A.5.24-A.5.28', 'ITR-034', 'No tested incident response plan', 'operational', 3, 5, 'Incident Response Lead', 'Create and test IR playbooks for ransomware, BEC, and data breach.'),
  ('Incident Response', 2, 'Is incident communication (internal/external/regulatory) well planned?', 'medium', 'Stakeholders, customers, or regulators are not informed appropriately during incidents. Root causes: No comms plan; unclear legal/privacy escalation.', 'Communication', 'NIST CSF RS.CO; ISO 27001 A.5.24-A.5.28', 'ITR-035', 'Poor incident communication', 'operational', 2, 5, 'IR Lead / Legal / Communications', 'Prepare communication templates and escalation triggers.'),
  ('Data Protection', 1, 'Is sensitive data classified according to a defined scheme?', 'high', 'Sensitive data is not identified or handled according to sensitivity. Root causes: No classification scheme; no ownership; limited DLP.', 'Data Classification', 'NIST CSF ID.AM/PR.DS; ISO 27001 A.5.12/A.5.13', 'ITR-036', 'No data classification', 'compliance', 4, 4, 'Data Owner / Compliance', 'Define classification levels and apply labels to sensitive data.'),
  ('Data Protection', 2, 'Is sensitive data encrypted at rest and in transit?', 'high', 'Sensitive data is stored or transmitted without adequate encryption. Root causes: Legacy systems; misconfiguration; no encryption standard.', 'Encryption', 'NIST CSF PR.DS; ISO 27001 A.8.24', 'ITR-037', 'Sensitive data not encrypted', 'compliance', 3, 5, 'Infrastructure / Application Owner', 'Validate encryption for critical systems and data stores.'),
  ('Backup & Recovery', 1, 'Are backups completed successfully and verified as complete?', 'high', 'Critical systems cannot be restored because backups failed or missed data. Root causes: No monitoring; misconfigured jobs; undocumented scope.', 'Backups', 'NIST CSF PR.DS/RC.RP; ISO 27001 A.8.13', 'ITR-038', 'Backups fail or are incomplete', 'operational', 3, 5, 'Backup Administrator', 'Monitor backup success and test restores for critical systems.'),
  ('Backup & Recovery', 2, 'Is the disaster recovery plan tested regularly?', 'high', 'Recovery procedures exist but have not been validated. Root causes: No DR exercises; unclear RTO/RPO; limited ownership.', 'Disaster Recovery', 'NIST CSF RC.RP; ISO 27001 A.5.30', 'ITR-039', 'DR plan not tested', 'operational', 3, 5, 'Infrastructure / Business Continuity', 'Run annual DR tests and track remediation actions.'),
  ('Business Continuity', 1, 'Is there a documented business continuity plan for critical services?', 'high', 'Business teams lack manual workaround or continuity procedures. Root causes: No BIA; limited ownership; no exercises.', 'Continuity Planning', 'NIST CSF RC.RP; ISO 27001 A.5.29/A.5.30', 'ITR-040', 'No business continuity plan for critical services', 'operational', 3, 5, 'Business Continuity Manager', 'Complete BIA and continuity plans for critical processes.'),
  ('Third Party & Supply Chain', 1, 'Are third-party vendors assessed for security weaknesses?', 'high', 'A third-party provider exposes data or becomes a route into the environment. Root causes: No supplier due diligence; weak contracts; no monitoring.', 'Supplier Security', 'NIST CSF GV.SC; ISO 27001 A.5.19-A.5.23', 'ITR-041', 'Vendor security weakness', 'operational', 3, 5, 'Procurement / Vendor Owner', 'Tier suppliers by criticality and assess high-risk suppliers annually.'),
  ('Third Party & Supply Chain', 2, 'Is third-party access to systems/data actively managed and monitored?', 'critical', 'Vendors retain remote or admin access after projects end. Root causes: No access expiry; no vendor reviews; shared accounts.', 'Third-Party Access', 'NIST CSF PR.AA/GV.SC; ISO 27001 A.5.19/A.5.22', 'ITR-042', 'Unmanaged third-party access', 'operational', 4, 5, 'IT Security / Vendor Owner', 'Review third-party accounts and enforce expiry dates.'),
  ('Asset Management', 1, 'Is the IT asset inventory complete and up to date?', 'high', 'IT cannot confirm all devices, servers, applications, or owners. Root causes: Manual inventory; shadow IT; no CMDB process.', 'Asset Inventory', 'NIST CSF ID.AM; ISO 27001 A.5.9', 'ITR-043', 'Incomplete IT asset inventory', 'operational', 4, 4, 'IT Operations', 'Build a complete asset inventory and reconcile monthly.'),
  ('Asset Management', 2, 'Is system configuration managed to prevent drift from baseline?', 'medium', 'Systems deviate from approved secure baselines over time. Root causes: Manual changes; no configuration monitoring; exceptions unmanaged.', 'Configuration Management', 'NIST CSF PR.PS; ISO 27001 A.8.9', 'ITR-044', 'Configuration drift', 'operational', 3, 4, 'Infrastructure / Security', 'Define baseline standards and monitor compliance.'),
  ('Compliance & Legal', 1, 'Is the organisation compliant with applicable privacy legislation (POPIA/GDPR)?', 'high', 'Personal information is processed without adequate controls or evidence. Root causes: Unclear processing inventory; weak retention; poor data subject processes.', 'Privacy Compliance', 'NIST CSF GV.OC/PR.DS; ISO 27001 A.5', 'ITR-045', 'POPIA/privacy non-compliance', 'compliance', 3, 5, 'Compliance / Information Officer', 'Document personal information processing and align retention controls.'),
  ('Compliance & Legal', 2, 'Is software licensing tracked and compliant?', 'medium', 'Software is installed without valid licensing or approved procurement. Root causes: Poor asset tracking; user-installed apps; no license review.', 'Software Licensing', 'NIST CSF ID.AM; ISO 27001 A.5.32', 'ITR-046', 'Unlicensed or non-compliant software', 'compliance', 3, 3, 'IT Asset Manager', 'Implement software asset management and periodic reconciliation.'),
  ('Physical & Environmental', 1, 'Is physical access to server/network rooms restricted to authorized personnel?', 'medium', 'Unauthorised staff or visitors access critical infrastructure areas. Root causes: Weak access control; shared keys; no visitor logging.', 'Physical Security', 'NIST CSF PR.PS; ISO 27001 A.7', 'ITR-047', 'Unauthorized access to server/network rooms', 'operational', 2, 5, 'Facilities / IT Infrastructure', 'Restrict and review access to IT rooms quarterly.'),
  ('Physical & Environmental', 2, 'Are power/cooling/environmental controls in place for critical infrastructure?', 'medium', 'Equipment fails due to power outage, overheating, or water damage. Root causes: No UPS/generator; poor monitoring; inadequate maintenance.', 'Power & Environment', 'NIST CSF PR.IR/RC.RP; ISO 27001 A.7', 'ITR-048', 'Power, cooling, or environmental failure', 'operational', 3, 4, 'Facilities / Infrastructure', 'Validate power and environmental controls for critical sites.'),
  ('Operational IT', 1, 'Is operational IT documentation (runbooks, diagrams, procedures) current and adequate?', 'medium', 'Key systems lack runbooks, diagrams, support procedures, or ownership records. Root causes: Time pressure; undocumented changes; staff turnover.', 'Documentation', 'NIST CSF GV.RR/PR.PS; ISO 27001 A.5', 'ITR-049', 'Poor operational documentation', 'operational', 4, 3, 'IT Operations Manager', 'Maintain runbooks for critical systems and review quarterly.'),
  ('Operational IT', 2, 'Is key-person dependency risk mitigated (cross-training, documentation)?', 'medium', 'Only one person understands a critical system or process. Root causes: Limited cross-training; poor documentation; staffing constraints.', 'Skills & Capacity', 'NIST CSF GV.RR; ISO 27001 Clause 7', 'ITR-050', 'Key-person dependency', 'operational', 3, 4, 'IT Manager', 'Create skills matrix and cross-train support staff.'),
  ('Operational IT', 3, 'Is incident/problem management handled through a formal service management process?', 'medium', 'Recurring incidents are handled individually without root-cause removal. Root causes: No ITSM process; weak categorization; no PIR cadence.', 'Service Management', 'NIST CSF RS.AN/RS.MI; ISO 27001 A.5', 'ITR-051', 'Poor incident/problem management', 'operational', 3, 4, 'Service Desk / IT Operations', 'Introduce recurring incident analysis and problem records.'),
  ('Financial & Project', 1, 'Is the IT/security budget sufficient for the organisation''s needs?', 'medium', 'Critical security improvements are deferred due to budget limitations. Root causes: No risk-based budget; competing priorities; unclear ROI.', 'IT Budget', 'NIST CSF GV.RM/GV.RR; ISO 27001 Clause 6', 'ITR-052', 'Insufficient IT/security budget', 'financial', 3, 4, 'CIO / Finance', 'Link investment requests to risk reduction and business impact.'),
  ('Financial & Project', 2, 'Are IT projects delivered on time and within scope/budget?', 'medium', 'Critical technology projects overrun, fail, or deliver insecure outcomes. Root causes: Poor scope control; weak requirements; lack of security review.', 'Project Delivery', 'NIST CSF GV.OC/GV.RR; ISO 27001 Clause 6/8', 'ITR-053', 'IT project failure or delay', 'financial', 3, 4, 'Project Manager / Sponsor', 'Include security and operational readiness gates in key projects.'),
  ('Emerging Technology', 1, 'Is the use of generative AI tools governed by policy?', 'high', 'Staff paste sensitive data into unsanctioned AI tools. Root causes: No AI usage policy; limited awareness; shadow IT.', 'AI Usage', 'NIST CSF GV.PO/PR.DS; ISO 27001 A.5/A.8', 'ITR-054', 'Uncontrolled use of generative AI tools', 'technical', 4, 4, 'IT Governance / Security', 'Publish AI usage rules and monitor unsanctioned AI services.'),
  ('Emerging Technology', 2, 'Are IoT/smart devices on the corporate network inventoried and managed?', 'medium', 'Cameras, printers, sensors, or smart devices connect without security controls. Root causes: No IoT inventory; default passwords; flat network.', 'IoT / Smart Devices', 'NIST CSF ID.AM/PR.PS; ISO 27001 A.8', 'ITR-055', 'Unmanaged IoT devices on corporate network', 'technical', 3, 4, 'Network / Facilities / IT', 'Segment IoT devices and maintain ownership inventory.')
;
